name: Deploy to Development Environment

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build the Static Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npx parcel build src/index.html --dist-dir dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Directory where the built files are located

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
